get_price_mart:
  outputs:

    dqx:
      type: trino
      method: none
      user: tig
      database: iceberg
      host: trino.trino.svc.cluster.local
      port: 8080
      schema: dqx
      threads: 3

  target: dqx

