get_price_mart:
  outputs:

    dqx:
      type: trino
      method: none
      user: tig
      database: iceberg
      host: trino.mynet
      port: 80
      schema: dqx
      threads: 3

  target: dqx

